/*
 * Generated by Scripts/genFixedRFFTTwiddleCoefs.py; do not edit.
 * SPDX-License-Identifier: Apache-2.0
 */

#include "arm_compiler_specific.h"
#include "dsp/transform_functions.h"
#include "arm_const_structs.h"

#if !defined(ARM_MATH_NEON)

static const q31_t arm_rfft_realCoefAQ31_128[130]
    ARM_DSP_TABLE_ATTRIBUTE = {
    (q31_t)0x40000000, (q31_t)0xc0000000, (q31_t)0x3cdc1342, (q31_t)0xc013bc39,
    (q31_t)0x39ba1651, (q31_t)0xc04ee4b8, (q31_t)0x369bf7c9, (q31_t)0xc0b15502,
    (q31_t)0x3383a3e2, (q31_t)0xc13ad060, (q31_t)0x30730342, (q31_t)0xc1eb0209,
    (q31_t)0x2d6bf9d1, (q31_t)0xc2c17d52, (q31_t)0x2a70658a, (q31_t)0xc3bdbdf6,
    (q31_t)0x27821d59, (q31_t)0xc4df2862, (q31_t)0x24a2eff6, (q31_t)0xc6250a18,
    (q31_t)0x21d4a2c8, (q31_t)0xc78e9a1d, (q31_t)0x1f18f0ce, (q31_t)0xc91af976,
    (q31_t)0x1c71898d, (q31_t)0xcac933ae, (q31_t)0x19e01006, (q31_t)0xcc983f70,
    (q31_t)0x176619b6, (q31_t)0xce86ff2a, (q31_t)0x15052d97, (q31_t)0xd09441bb,
    (q31_t)0x12bec333, (q31_t)0xd2bec333, (q31_t)0x109441bb, (q31_t)0xd5052d97,
    (q31_t)0xe86ff2a, (q31_t)0xd76619b6, (q31_t)0xc983f70, (q31_t)0xd9e01006,
    (q31_t)0xac933ae, (q31_t)0xdc71898d, (q31_t)0x91af976, (q31_t)0xdf18f0ce,
    (q31_t)0x78e9a1d, (q31_t)0xe1d4a2c8, (q31_t)0x6250a18, (q31_t)0xe4a2eff6,
    (q31_t)0x4df2862, (q31_t)0xe7821d59, (q31_t)0x3bdbdf6, (q31_t)0xea70658a,
    (q31_t)0x2c17d52, (q31_t)0xed6bf9d1, (q31_t)0x1eb0209, (q31_t)0xf0730342,
    (q31_t)0x13ad060, (q31_t)0xf383a3e2, (q31_t)0xb15502, (q31_t)0xf69bf7c9,
    (q31_t)0x4ee4b8, (q31_t)0xf9ba1651, (q31_t)0x13bc39, (q31_t)0xfcdc1342,
    (q31_t)0x0, (q31_t)0x0, (q31_t)0x13bc39, (q31_t)0x323ecbe,
    (q31_t)0x4ee4b8, (q31_t)0x645e9af, (q31_t)0xb15502, (q31_t)0x9640837,
    (q31_t)0x13ad060, (q31_t)0xc7c5c1e, (q31_t)0x1eb0209, (q31_t)0xf8cfcbe,
    (q31_t)0x2c17d52, (q31_t)0x1294062f, (q31_t)0x3bdbdf6, (q31_t)0x158f9a76,
    (q31_t)0x4df2862, (q31_t)0x187de2a7, (q31_t)0x6250a18, (q31_t)0x1b5d100a,
    (q31_t)0x78e9a1d, (q31_t)0x1e2b5d38, (q31_t)0x91af976, (q31_t)0x20e70f32,
    (q31_t)0xac933ae, (q31_t)0x238e7673, (q31_t)0xc983f70, (q31_t)0x261feffa,
    (q31_t)0xe86ff2a, (q31_t)0x2899e64a, (q31_t)0x109441bb, (q31_t)0x2afad269,
    (q31_t)0x12bec333, (q31_t)0x2d413ccd, (q31_t)0x15052d97, (q31_t)0x2f6bbe45,
    (q31_t)0x176619b6, (q31_t)0x317900d6, (q31_t)0x19e01006, (q31_t)0x3367c090,
    (q31_t)0x1c71898d, (q31_t)0x3536cc52, (q31_t)0x1f18f0ce, (q31_t)0x36e5068a,
    (q31_t)0x21d4a2c8, (q31_t)0x387165e3, (q31_t)0x24a2eff6, (q31_t)0x39daf5e8,
    (q31_t)0x27821d59, (q31_t)0x3b20d79e, (q31_t)0x2a70658a, (q31_t)0x3c42420a,
    (q31_t)0x2d6bf9d1, (q31_t)0x3d3e82ae, (q31_t)0x30730342, (q31_t)0x3e14fdf7,
    (q31_t)0x3383a3e2, (q31_t)0x3ec52fa0, (q31_t)0x369bf7c9, (q31_t)0x3f4eaafe,
    (q31_t)0x39ba1651, (q31_t)0x3fb11b48, (q31_t)0x3cdc1342, (q31_t)0x3fec43c7,
    (q31_t)0x0, (q31_t)0x0,
};

static const q31_t arm_rfft_realCoefBQ31_128[130]
    ARM_DSP_TABLE_ATTRIBUTE = {
    (q31_t)0x40000000, (q31_t)0x40000000, (q31_t)0x4323ecbe, (q31_t)0x3fec43c7,
    (q31_t)0x4645e9af, (q31_t)0x3fb11b48, (q31_t)0x49640837, (q31_t)0x3f4eaafe,
    (q31_t)0x4c7c5c1e, (q31_t)0x3ec52fa0, (q31_t)0x4f8cfcbe, (q31_t)0x3e14fdf7,
    (q31_t)0x5294062f, (q31_t)0x3d3e82ae, (q31_t)0x558f9a76, (q31_t)0x3c42420a,
    (q31_t)0x587de2a7, (q31_t)0x3b20d79e, (q31_t)0x5b5d100a, (q31_t)0x39daf5e8,
    (q31_t)0x5e2b5d38, (q31_t)0x387165e3, (q31_t)0x60e70f32, (q31_t)0x36e5068a,
    (q31_t)0x638e7673, (q31_t)0x3536cc52, (q31_t)0x661feffa, (q31_t)0x3367c090,
    (q31_t)0x6899e64a, (q31_t)0x317900d6, (q31_t)0x6afad269, (q31_t)0x2f6bbe45,
    (q31_t)0x6d413ccd, (q31_t)0x2d413ccd, (q31_t)0x6f6bbe45, (q31_t)0x2afad269,
    (q31_t)0x717900d6, (q31_t)0x2899e64a, (q31_t)0x7367c090, (q31_t)0x261feffa,
    (q31_t)0x7536cc52, (q31_t)0x238e7673, (q31_t)0x76e5068a, (q31_t)0x20e70f32,
    (q31_t)0x787165e3, (q31_t)0x1e2b5d38, (q31_t)0x79daf5e8, (q31_t)0x1b5d100a,
    (q31_t)0x7b20d79e, (q31_t)0x187de2a7, (q31_t)0x7c42420a, (q31_t)0x158f9a76,
    (q31_t)0x7d3e82ae, (q31_t)0x1294062f, (q31_t)0x7e14fdf7, (q31_t)0xf8cfcbe,
    (q31_t)0x7ec52fa0, (q31_t)0xc7c5c1e, (q31_t)0x7f4eaafe, (q31_t)0x9640837,
    (q31_t)0x7fb11b48, (q31_t)0x645e9af, (q31_t)0x7fec43c7, (q31_t)0x323ecbe,
    (q31_t)0x7fffffff, (q31_t)0x0, (q31_t)0x7fec43c7, (q31_t)0xfcdc1342,
    (q31_t)0x7fb11b48, (q31_t)0xf9ba1651, (q31_t)0x7f4eaafe, (q31_t)0xf69bf7c9,
    (q31_t)0x7ec52fa0, (q31_t)0xf383a3e2, (q31_t)0x7e14fdf7, (q31_t)0xf0730342,
    (q31_t)0x7d3e82ae, (q31_t)0xed6bf9d1, (q31_t)0x7c42420a, (q31_t)0xea70658a,
    (q31_t)0x7b20d79e, (q31_t)0xe7821d59, (q31_t)0x79daf5e8, (q31_t)0xe4a2eff6,
    (q31_t)0x787165e3, (q31_t)0xe1d4a2c8, (q31_t)0x76e5068a, (q31_t)0xdf18f0ce,
    (q31_t)0x7536cc52, (q31_t)0xdc71898d, (q31_t)0x7367c090, (q31_t)0xd9e01006,
    (q31_t)0x717900d6, (q31_t)0xd76619b6, (q31_t)0x6f6bbe45, (q31_t)0xd5052d97,
    (q31_t)0x6d413ccd, (q31_t)0xd2bec333, (q31_t)0x6afad269, (q31_t)0xd09441bb,
    (q31_t)0x6899e64a, (q31_t)0xce86ff2a, (q31_t)0x661feffa, (q31_t)0xcc983f70,
    (q31_t)0x638e7673, (q31_t)0xcac933ae, (q31_t)0x60e70f32, (q31_t)0xc91af976,
    (q31_t)0x5e2b5d38, (q31_t)0xc78e9a1d, (q31_t)0x5b5d100a, (q31_t)0xc6250a18,
    (q31_t)0x587de2a7, (q31_t)0xc4df2862, (q31_t)0x558f9a76, (q31_t)0xc3bdbdf6,
    (q31_t)0x5294062f, (q31_t)0xc2c17d52, (q31_t)0x4f8cfcbe, (q31_t)0xc1eb0209,
    (q31_t)0x4c7c5c1e, (q31_t)0xc13ad060, (q31_t)0x49640837, (q31_t)0xc0b15502,
    (q31_t)0x4645e9af, (q31_t)0xc04ee4b8, (q31_t)0x4323ecbe, (q31_t)0xc013bc39,
    (q31_t)0x0, (q31_t)0x0,
};

ARM_DSP_ATTRIBUTE arm_status arm_rfft_init_128_q31(
    arm_rfft_instance_q31 *S,
    uint32_t ifftFlagR,
    uint32_t bitReverseFlag)
{
    S->fftLenReal = (uint16_t)128;
    S->pTwiddleAReal = arm_rfft_realCoefAQ31_128;
    S->pTwiddleBReal = arm_rfft_realCoefBQ31_128;
    S->ifftFlagR = (uint8_t)ifftFlagR;
    S->bitReverseFlagR = (uint8_t)bitReverseFlag;
    S->twidCoefRModifier = 1U;

#if defined(ARM_MATH_MVEI) && !defined(ARM_MATH_AUTOVECTORIZE)
    return arm_cfft_init_64_q31(&S->cfftInst);
#else
    S->pCfft = &arm_cfft_sR_q31_len64;
    return ARM_MATH_SUCCESS;
#endif
}

#endif /* !ARM_MATH_NEON */
