/*
 * Generated by Scripts/genFixedRFFTTwiddleCoefs.py; do not edit.
 * SPDX-License-Identifier: Apache-2.0
 */

#include "arm_compiler_specific.h"
#include "dsp/transform_functions.h"
#include "arm_const_structs.h"

#if !defined(ARM_MATH_NEON)

static const q15_t __ALIGNED(4) arm_rfft_realCoefAQ15_32[34]
    ARM_DSP_TABLE_ATTRIBUTE = {
    (q15_t)0x4000, (q15_t)0xc000, (q15_t)0x3384, (q15_t)0xc13b, (q15_t)0x2782, (q15_t)0xc4df, (q15_t)0x1c72, (q15_t)0xcac9,
    (q15_t)0x12bf, (q15_t)0xd2bf, (q15_t)0xac9, (q15_t)0xdc72, (q15_t)0x4df, (q15_t)0xe782, (q15_t)0x13b, (q15_t)0xf384,
    (q15_t)0x0, (q15_t)0x0, (q15_t)0x13b, (q15_t)0xc7c, (q15_t)0x4df, (q15_t)0x187e, (q15_t)0xac9, (q15_t)0x238e,
    (q15_t)0x12bf, (q15_t)0x2d41, (q15_t)0x1c72, (q15_t)0x3537, (q15_t)0x2782, (q15_t)0x3b21, (q15_t)0x3384, (q15_t)0x3ec5,
    (q15_t)0x0, (q15_t)0x0,
};

static const q15_t __ALIGNED(4) arm_rfft_realCoefBQ15_32[34]
    ARM_DSP_TABLE_ATTRIBUTE = {
    (q15_t)0x4000, (q15_t)0x4000, (q15_t)0x4c7c, (q15_t)0x3ec5, (q15_t)0x587e, (q15_t)0x3b21, (q15_t)0x638e, (q15_t)0x3537,
    (q15_t)0x6d41, (q15_t)0x2d41, (q15_t)0x7537, (q15_t)0x238e, (q15_t)0x7b21, (q15_t)0x187e, (q15_t)0x7ec5, (q15_t)0xc7c,
    (q15_t)0x7fff, (q15_t)0x0, (q15_t)0x7ec5, (q15_t)0xf384, (q15_t)0x7b21, (q15_t)0xe782, (q15_t)0x7537, (q15_t)0xdc72,
    (q15_t)0x6d41, (q15_t)0xd2bf, (q15_t)0x638e, (q15_t)0xcac9, (q15_t)0x587e, (q15_t)0xc4df, (q15_t)0x4c7c, (q15_t)0xc13b,
    (q15_t)0x0, (q15_t)0x0,
};

ARM_DSP_ATTRIBUTE arm_status arm_rfft_init_32_q15(
    arm_rfft_instance_q15 *S,
    uint32_t ifftFlagR,
    uint32_t bitReverseFlag)
{
    S->fftLenReal = (uint16_t)32;
    S->pTwiddleAReal = arm_rfft_realCoefAQ15_32;
    S->pTwiddleBReal = arm_rfft_realCoefBQ15_32;
    S->ifftFlagR = (uint8_t)ifftFlagR;
    S->bitReverseFlagR = (uint8_t)bitReverseFlag;
    S->twidCoefRModifier = 1U;

#if defined(ARM_MATH_MVEI) && !defined(ARM_MATH_AUTOVECTORIZE)
    return arm_cfft_init_16_q15(&S->cfftInst);
#else
    S->pCfft = &arm_cfft_sR_q15_len16;
    return ARM_MATH_SUCCESS;
#endif
}

#endif /* !ARM_MATH_NEON */
