/*
 * Generated by Scripts/genFixedRFFTTwiddleCoefs.py; do not edit.
 * SPDX-License-Identifier: Apache-2.0
 */

#include "arm_compiler_specific.h"
#include "dsp/transform_functions.h"
#include "arm_const_structs.h"

#if !defined(ARM_MATH_NEON)

static const q31_t arm_rfft_realCoefAQ31_32[34]
    ARM_DSP_TABLE_ATTRIBUTE = {
    (q31_t)0x40000000, (q31_t)0xc0000000, (q31_t)0x3383a3e2, (q31_t)0xc13ad060,
    (q31_t)0x27821d59, (q31_t)0xc4df2862, (q31_t)0x1c71898d, (q31_t)0xcac933ae,
    (q31_t)0x12bec333, (q31_t)0xd2bec333, (q31_t)0xac933ae, (q31_t)0xdc71898d,
    (q31_t)0x4df2862, (q31_t)0xe7821d59, (q31_t)0x13ad060, (q31_t)0xf383a3e2,
    (q31_t)0x0, (q31_t)0x0, (q31_t)0x13ad060, (q31_t)0xc7c5c1e,
    (q31_t)0x4df2862, (q31_t)0x187de2a7, (q31_t)0xac933ae, (q31_t)0x238e7673,
    (q31_t)0x12bec333, (q31_t)0x2d413ccd, (q31_t)0x1c71898d, (q31_t)0x3536cc52,
    (q31_t)0x27821d59, (q31_t)0x3b20d79e, (q31_t)0x3383a3e2, (q31_t)0x3ec52fa0,
    (q31_t)0x0, (q31_t)0x0,
};

static const q31_t arm_rfft_realCoefBQ31_32[34]
    ARM_DSP_TABLE_ATTRIBUTE = {
    (q31_t)0x40000000, (q31_t)0x40000000, (q31_t)0x4c7c5c1e, (q31_t)0x3ec52fa0,
    (q31_t)0x587de2a7, (q31_t)0x3b20d79e, (q31_t)0x638e7673, (q31_t)0x3536cc52,
    (q31_t)0x6d413ccd, (q31_t)0x2d413ccd, (q31_t)0x7536cc52, (q31_t)0x238e7673,
    (q31_t)0x7b20d79e, (q31_t)0x187de2a7, (q31_t)0x7ec52fa0, (q31_t)0xc7c5c1e,
    (q31_t)0x7fffffff, (q31_t)0x0, (q31_t)0x7ec52fa0, (q31_t)0xf383a3e2,
    (q31_t)0x7b20d79e, (q31_t)0xe7821d59, (q31_t)0x7536cc52, (q31_t)0xdc71898d,
    (q31_t)0x6d413ccd, (q31_t)0xd2bec333, (q31_t)0x638e7673, (q31_t)0xcac933ae,
    (q31_t)0x587de2a7, (q31_t)0xc4df2862, (q31_t)0x4c7c5c1e, (q31_t)0xc13ad060,
    (q31_t)0x0, (q31_t)0x0,
};

ARM_DSP_ATTRIBUTE arm_status arm_rfft_init_32_q31(
    arm_rfft_instance_q31 *S,
    uint32_t ifftFlagR,
    uint32_t bitReverseFlag)
{
    S->fftLenReal = (uint16_t)32;
    S->pTwiddleAReal = arm_rfft_realCoefAQ31_32;
    S->pTwiddleBReal = arm_rfft_realCoefBQ31_32;
    S->ifftFlagR = (uint8_t)ifftFlagR;
    S->bitReverseFlagR = (uint8_t)bitReverseFlag;
    S->twidCoefRModifier = 1U;

#if defined(ARM_MATH_MVEI) && !defined(ARM_MATH_AUTOVECTORIZE)
    return arm_cfft_init_16_q31(&S->cfftInst);
#else
    S->pCfft = &arm_cfft_sR_q31_len16;
    return ARM_MATH_SUCCESS;
#endif
}

#endif /* !ARM_MATH_NEON */
