/*
 * Generated by Scripts/genFixedRFFTTwiddleCoefs.py; do not edit.
 * SPDX-License-Identifier: Apache-2.0
 */

#include "arm_compiler_specific.h"
#include "dsp/transform_functions.h"
#include "arm_const_structs.h"

#if !defined(ARM_MATH_NEON)

static const q15_t __ALIGNED(4) arm_rfft_realCoefAQ15_64[66]
    ARM_DSP_TABLE_ATTRIBUTE = {
    (q15_t)0x4000, (q15_t)0xc000, (q15_t)0x39ba, (q15_t)0xc04f, (q15_t)0x3384, (q15_t)0xc13b, (q15_t)0x2d6c, (q15_t)0xc2c1,
    (q15_t)0x2782, (q15_t)0xc4df, (q15_t)0x21d5, (q15_t)0xc78f, (q15_t)0x1c72, (q15_t)0xcac9, (q15_t)0x1766, (q15_t)0xce87,
    (q15_t)0x12bf, (q15_t)0xd2bf, (q15_t)0xe87, (q15_t)0xd766, (q15_t)0xac9, (q15_t)0xdc72, (q15_t)0x78f, (q15_t)0xe1d5,
    (q15_t)0x4df, (q15_t)0xe782, (q15_t)0x2c1, (q15_t)0xed6c, (q15_t)0x13b, (q15_t)0xf384, (q15_t)0x4f, (q15_t)0xf9ba,
    (q15_t)0x0, (q15_t)0x0, (q15_t)0x4f, (q15_t)0x646, (q15_t)0x13b, (q15_t)0xc7c, (q15_t)0x2c1, (q15_t)0x1294,
    (q15_t)0x4df, (q15_t)0x187e, (q15_t)0x78f, (q15_t)0x1e2b, (q15_t)0xac9, (q15_t)0x238e, (q15_t)0xe87, (q15_t)0x289a,
    (q15_t)0x12bf, (q15_t)0x2d41, (q15_t)0x1766, (q15_t)0x3179, (q15_t)0x1c72, (q15_t)0x3537, (q15_t)0x21d5, (q15_t)0x3871,
    (q15_t)0x2782, (q15_t)0x3b21, (q15_t)0x2d6c, (q15_t)0x3d3f, (q15_t)0x3384, (q15_t)0x3ec5, (q15_t)0x39ba, (q15_t)0x3fb1,
    (q15_t)0x0, (q15_t)0x0,
};

static const q15_t __ALIGNED(4) arm_rfft_realCoefBQ15_64[66]
    ARM_DSP_TABLE_ATTRIBUTE = {
    (q15_t)0x4000, (q15_t)0x4000, (q15_t)0x4646, (q15_t)0x3fb1, (q15_t)0x4c7c, (q15_t)0x3ec5, (q15_t)0x5294, (q15_t)0x3d3f,
    (q15_t)0x587e, (q15_t)0x3b21, (q15_t)0x5e2b, (q15_t)0x3871, (q15_t)0x638e, (q15_t)0x3537, (q15_t)0x689a, (q15_t)0x3179,
    (q15_t)0x6d41, (q15_t)0x2d41, (q15_t)0x7179, (q15_t)0x289a, (q15_t)0x7537, (q15_t)0x238e, (q15_t)0x7871, (q15_t)0x1e2b,
    (q15_t)0x7b21, (q15_t)0x187e, (q15_t)0x7d3f, (q15_t)0x1294, (q15_t)0x7ec5, (q15_t)0xc7c, (q15_t)0x7fb1, (q15_t)0x646,
    (q15_t)0x7fff, (q15_t)0x0, (q15_t)0x7fb1, (q15_t)0xf9ba, (q15_t)0x7ec5, (q15_t)0xf384, (q15_t)0x7d3f, (q15_t)0xed6c,
    (q15_t)0x7b21, (q15_t)0xe782, (q15_t)0x7871, (q15_t)0xe1d5, (q15_t)0x7537, (q15_t)0xdc72, (q15_t)0x7179, (q15_t)0xd766,
    (q15_t)0x6d41, (q15_t)0xd2bf, (q15_t)0x689a, (q15_t)0xce87, (q15_t)0x638e, (q15_t)0xcac9, (q15_t)0x5e2b, (q15_t)0xc78f,
    (q15_t)0x587e, (q15_t)0xc4df, (q15_t)0x5294, (q15_t)0xc2c1, (q15_t)0x4c7c, (q15_t)0xc13b, (q15_t)0x4646, (q15_t)0xc04f,
    (q15_t)0x0, (q15_t)0x0,
};

ARM_DSP_ATTRIBUTE arm_status arm_rfft_init_64_q15(
    arm_rfft_instance_q15 *S,
    uint32_t ifftFlagR,
    uint32_t bitReverseFlag)
{
    S->fftLenReal = (uint16_t)64;
    S->pTwiddleAReal = arm_rfft_realCoefAQ15_64;
    S->pTwiddleBReal = arm_rfft_realCoefBQ15_64;
    S->ifftFlagR = (uint8_t)ifftFlagR;
    S->bitReverseFlagR = (uint8_t)bitReverseFlag;
    S->twidCoefRModifier = 1U;

#if defined(ARM_MATH_MVEI) && !defined(ARM_MATH_AUTOVECTORIZE)
    return arm_cfft_init_32_q15(&S->cfftInst);
#else
    S->pCfft = &arm_cfft_sR_q15_len32;
    return ARM_MATH_SUCCESS;
#endif
}

#endif /* !ARM_MATH_NEON */
