#!/usr/bin/env python3
"""Generate compact per-length Q15/Q31 RFFT coefficient tables.

The compact tables are exact strided subsets of CMSIS-DSP's 8192-entry
master tables.  This preserves every fixed-point coefficient bit-for-bit.
Two zero guard elements are appended because the handwritten MVE forward
split kernels issue one final full-vector coefficient load before replacing
the DC/Nyquist output pair.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MASTER = ROOT / "Source" / "CommonTables" / "arm_common_tables.c"
OUTPUT = ROOT / "Source" / "TransformFunctions" / "RFFTFixedTables"
LENGTHS = (32, 64, 128, 256, 512, 1024, 2048, 4096, 8192)


def read_master(name: str, ctype: str) -> list[str]:
    source = MASTER.read_text(encoding="utf-8-sig")
    # The master table holds 8192 coefficients, or 8194 when it carries the
    # two zero guard elements for the MVE split kernels' final vector load.
    match = re.search(
        rf"const\s+{ctype}\s+(?:__ALIGNED\(4\)\s+)?{name}\[(8192|8194)\]"
        rf"[^=]*=\s*\{{(.*?)\n\}};",
        source,
        re.DOTALL,
    )
    if match is None:
        raise RuntimeError(f"cannot find {name}[8192] or {name}[8194] in {MASTER}")
    declared = int(match.group(1))
    values = re.findall(rf"\({ctype}\)(0x[0-9a-fA-F]+)", match.group(2))
    if len(values) != declared:
        raise RuntimeError(f"expected {declared} values for {name}, found {len(values)}")
    if declared == 8194 and values[8192:] != ["0x0", "0x0"]:
        raise RuntimeError(f"expected two zero guards at the end of {name}")
    return values[:8192]


def format_values(values: list[str], ctype: str) -> str:
    width = 8 if ctype == "q15_t" else 4
    rendered = [f"({ctype}){value.lower()}" for value in values]
    return "\n".join(
        "    " + ", ".join(rendered[i : i + width]) + ","
        for i in range(0, len(rendered), width)
    )


def render(dtype: str, length: int, a_master: list[str], b_master: list[str]) -> str:
    ctype = f"{dtype}_t"
    modifier = 8192 // length
    # Each logical coefficient is a real/imaginary pair. The modifier strides
    # between pairs, never between the two lanes inside one pair.
    source_indices = [
        2 * pair * modifier + lane
        for pair in range(length // 2)
        for lane in (0, 1)
    ]
    a_values = [a_master[i] for i in source_indices] + ["0x0", "0x0"]
    b_values = [b_master[i] for i in source_indices] + ["0x0", "0x0"]
    cfft_length = length // 2
    alignment = " __ALIGNED(4)" if dtype == "q15" else ""
    return f"""/*
 * Generated by Scripts/genFixedRFFTTwiddleCoefs.py; do not edit.
 * SPDX-License-Identifier: Apache-2.0
 */

#include "arm_compiler_specific.h"
#include "dsp/transform_functions.h"
#include "arm_const_structs.h"

#if !defined(ARM_MATH_NEON)

static const {ctype}{alignment} arm_rfft_realCoefA{dtype.upper()}_{length}[{length + 2}]
    ARM_DSP_TABLE_ATTRIBUTE = {{
{format_values(a_values, ctype)}
}};

static const {ctype}{alignment} arm_rfft_realCoefB{dtype.upper()}_{length}[{length + 2}]
    ARM_DSP_TABLE_ATTRIBUTE = {{
{format_values(b_values, ctype)}
}};

ARM_DSP_ATTRIBUTE arm_status arm_rfft_init_{length}_{dtype}(
    arm_rfft_instance_{dtype} *S,
    uint32_t ifftFlagR,
    uint32_t bitReverseFlag)
{{
    S->fftLenReal = (uint16_t){length};
    S->pTwiddleAReal = arm_rfft_realCoefA{dtype.upper()}_{length};
    S->pTwiddleBReal = arm_rfft_realCoefB{dtype.upper()}_{length};
    S->ifftFlagR = (uint8_t)ifftFlagR;
    S->bitReverseFlagR = (uint8_t)bitReverseFlag;
    S->twidCoefRModifier = 1U;

#if defined(ARM_MATH_MVEI) && !defined(ARM_MATH_AUTOVECTORIZE)
    return arm_cfft_init_{cfft_length}_{dtype}(&S->cfftInst);
#else
    S->pCfft = &arm_cfft_sR_{dtype}_len{cfft_length};
    return ARM_MATH_SUCCESS;
#endif
}}

#endif /* !ARM_MATH_NEON */
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if checked-in files differ")
    args = parser.parse_args()

    masters = {
        "q15": (
            read_master("realCoefAQ15", "q15_t"),
            read_master("realCoefBQ15", "q15_t"),
        ),
        "q31": (
            read_master("realCoefAQ31", "q31_t"),
            read_master("realCoefBQ31", "q31_t"),
        ),
    }
    stale: list[Path] = []
    if not args.check:
        OUTPUT.mkdir(parents=True, exist_ok=True)
    for dtype, (a_master, b_master) in masters.items():
        for length in LENGTHS:
            path = OUTPUT / f"arm_rfft_init_{length}_{dtype}.c"
            content = render(dtype, length, a_master, b_master)
            if args.check:
                if not path.is_file() or path.read_text(encoding="utf-8") != content:
                    stale.append(path.relative_to(ROOT))
            else:
                path.write_text(content, encoding="utf-8")
    if stale:
        for path in stale:
            print(f"stale generated file: {path}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
